version: '3'

services:
  voip:
    image: bersena/asterisk:1.0.0
    ports:
      - "5060:5060/udp"
      - "5060:5060"
      - "5038:5038/udp"
      - "5038:5038"
      - "8088:8088"
      - "18000-18100:18000-18100/udp"
    environment:
      - DEBUG=True
    volumes:
      - ./asterisk:/etc/asterisk
  app:
    build:
      context: app
    ports:
      - "8000:8000"